using System.Security.Cryptography;
using System.Text;

namespace GymFlow.Cli.Commands.Helpers;

/// <summary>
/// Generates environment configuration files
/// </summary>
public class EnvironmentGenerator
{
    public void Generate(string instanceName)
    {
        var envPath = Path.Combine(Directory.GetCurrentDirectory(), ".env");
        var envGymflowPath = Path.Combine(Directory.GetCurrentDirectory(), ".env.gymflow");

        // Generate main .env
        GenerateEnvFile(envPath, instanceName);

        // Generate secrets .env.gymflow
        GenerateSecretsFile(envGymflowPath, instanceName);

        Console.WriteLine($"Generated: {envPath}");
        Console.WriteLine($"Generated: {envGymflowPath}");
    }

    private void GenerateEnvFile(string path, string instanceName)
    {
        var content = $@"# GymFlow Lite Configuration
# Generated by gymflow CLI

# Database
POSTGRES_DB=gymflow_{SanitizeName(instanceName)}
POSTGRES_USER=gymflow
POSTGRES_PASSWORD= # See .env.gymflow

# Redis
REDIS_CONNECTION=redis:6379

# JWT
JWT_SECRET= # See .env.gymflow
JWT_ISSUER=https://{instanceName.ToLowerInvariant()}.example.com
JWT_AUDIENCE=https://{instanceName.ToLowerInvariant()}.example.com
";
        File.WriteAllText(path, content);
    }

    private void GenerateSecretsFile(string path, string instanceName)
    {
        var password = GenerateSecurePassword();
        var jwtSecret = GenerateSecurePassword(32);

        var content = $@"# GymFlow Secrets - DO NOT COMMIT TO VERSION CONTROL
# Generated on {DateTime.Now:yyyy-MM-dd HH:mm:ss}

POSTGRES_PASSWORD={password}
JWT_SECRET={jwtSecret}
";
        File.WriteAllText(path, content);
    }

    public static string GenerateSecurePassword(int length = 16)
    {
        const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
        var bytes = RandomNumberGenerator.GetBytes(length);
        var sb = new StringBuilder(length);
        foreach (var b in bytes)
        {
            sb.Append(chars[b % chars.Length]);
        }
        return sb.ToString();
    }

    private static string SanitizeName(string name)
    {
        return name.ToLowerInvariant()
            .Replace(" ", "-")
            .Replace("_", "-");
    }
}